# <font color=darkred>Laboratory 11: Linear Algebra using Numpy
</font>

In [ ]:
# Preamble script block to identify host, user, and kernel
import sys
! hostname
! whoami
print(sys.executable)
print(sys.version)
print(sys.version_info)

## Full name: 
## R#: 
## Title of the notebook:
## Date:
___

> ## [Link to Linear Algebra Codes using Numpy](https://numpy.org/doc/stable/reference/routines.linalg.html)
<div style="display: flex; justify-content: space-between;">
    <img src="https://miro.medium.com/v2/0*eF3twfWubEgjgS8_.png" alt="Image 1" width=45% height="200">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5wEnDpYTv5IZq1M2Jc24eZys3NhNEpdNUpA&s" alt="Image 2" width=45% height="200">
</div>



## Linear Algebra and Systems of Linear Equations
Numerous problems in engineering and science can be described or approximated by linear relationships. For example, if you combine resistors in a complicated circuit, you will obtain a system of linear relationships. Similarly, if you study small deformations of rigid structures, you will also get a system of relationships. In fact, it is difficult to think of any science or engineering field in which relationships of these kind are not fundamental. <br>
The study of linear relationship is contained in the field of linear algebra, and this chapter provides a basic overview of some basic linear algebraic vocabulary and concepts that are important for later chapters. Since this text does not assume any prior knowledge of linear algebra, some of the more abstract mathematical concepts and proofs on this topic have been omitted to make the material more accessible. However, the information in this chapter is in no way comprehensive and should not be considered a substitute for a full linear algebra course.<br>
### Vectors and Vector Norms
A vector in ℝ𝑛  is an 𝑛-tuple, or point, in ℝ𝑛. Vectors can be written horizontally (i.e., with the elements of the vector next to each other) in a row vector, or vertically (i.e., with the elements of the vector on top of each other) in a column vector. If the context of a vector is ambiguous, it usually means the vector is a column vector. The 𝑖-th element of a vector, 𝑣, is denoted by 𝑣𝑖. The transpose of a column vector is a row vector of the same length, and the transpose of a row vector is a column vector. In mathematics, the transpose is denoted by a superscript 𝑇, or 𝑣𝑇. The zero vector is the vector in ℝ𝑛 containing all zeros.<br>


The norm of a vector is a measure of its length. There are various ways to define the length of a vector, depending on the metric used (i.e., the distance formula chosen). The most common norm is the **𝐿2 norm**, which is calculated using the distance formula you may recall from grade school.

The **𝐿2 norm** of a vector **𝑣** is denoted by **‖𝑣‖₂** and is computed as:

$$‖𝑣‖₂ = \sqrt{\sum_{i} v_i^2}$$

This norm is sometimes referred to as the **Euclidean length**, representing the "physical" length of a vector in one-, two-, or three-dimensional space.

Another common norm is the **𝐿1 norm**, also known as the **"Manhattan Distance"**. It is computed as:

$$‖𝑣‖₁ = \sum_{i} |v_i|$$

The name "Manhattan Distance" comes from the grid-like road structure in New York City, where this metric is often used to calculate distances.

In general, the **p-norm** of a vector, **𝐿𝑝**, is defined as:

$$‖𝑣‖ₚ = \left(\sum_{i} |v_i|^p\right)^{1/p}$$

Lastly, the **𝐿∞ norm** is the **p-norm** where **𝑝=∞**. The **𝐿∞ norm** is denoted as **‖𝑣‖∞** and is equal to the maximum absolute value in the vector **𝑣**:

$$‖𝑣‖∞ = \max(|v_i|)$$
#### Examples

In [24]:
# Create a row vector and column vector, and show the shape of the vectors.
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


In [26]:
#Transpose the row vector we defined above into a column vector 
#Calculate the 𝐿1, 𝐿2, and 𝐿∞ norm of it. 
#Verify that the 𝐿∞ norm of a vector is equivalent to the maximum value of the elements in the vector.

from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


### Vector Addition and Multiplication

**Vector Addition** is defined as the pairwise addition of each element in the vectors being added. For example, if **𝑣** and **𝑤** are vectors in ℝⁿ, then **𝑢 = 𝑣 + 𝑤** is defined as:

$$𝑢𝑖 = 𝑣𝑖 + 𝑤𝑖$$

**Vector Multiplication** can be defined in several ways depending on the context. **Scalar multiplication** of a vector is the product of a vector and a scalar (i.e., a number in ℝ). Scalar multiplication is defined as the product of each element of the vector by the scalar. Specifically, if **𝛼** is a scalar and **𝑣** is a vector, then **𝑢 = 𝛼𝑣** is defined as:

$$𝑢𝑖 = 𝛼𝑣𝑖$$

Note that this is exactly how Python implements scalar multiplication with a vector.

### Note
Show that **𝑎(𝑣 + 𝑤) = 𝑎𝑣 + 𝑎𝑤** (i.e., scalar multiplication of a vector distributes across vector addition).

By vector addition, **𝑢 = 𝑣 + 𝑤** is the vector with:

$$𝑢𝑖 = 𝑣𝑖 + 𝑤𝑖$$

By scalar multiplication of a vector, **𝑥 = 𝛼𝑢** is the vector with:

$$𝑥𝑖 = 𝛼(𝑣𝑖 + 𝑤𝑖)$$

Since **𝛼**, **𝑣𝑖**, and **𝑤𝑖** are scalars, multiplication distributes, and:

$$𝑥𝑖 = 𝛼𝑣𝑖 + 𝛼𝑤𝑖$$

Therefore:

$$𝑎(𝑣 + 𝑤) = 𝑎𝑣 + 𝑎𝑤$$

### Dot Product

The **dot product** of two vectors is the sum of the products of the respective elements in each vector. It is denoted by **⋅**, and **𝑣⋅𝑤** is read as "v dot w." For vectors **𝑣** and **𝑤** in ℝⁿ, the dot product **𝑑 = 𝑣⋅𝑤** is defined as:

$$𝑑 = \sum_{𝑖=1}^{𝑛} 𝑣𝑖𝑤𝑖$$

The angle between two vectors, **𝜃**, is given by the formula:

$$𝑣⋅𝑤 = ‖𝑣‖₂‖𝑤‖₂ \cos𝜃$$

The dot product is a measure of how similarly directed the two vectors are. For example, the vectors **(1, 1)** and **(2, 2)** are parallel. If you compute the angle between them using the dot product, you will find that **𝜃 = 0**. If the angle between the vectors is **𝜃 = 𝜋/2**, then the vectors are said to be perpendicular (orthogonal), and the dot product is 0.
### Cross Product and Linear Combinations

The **cross product** between two vectors, **𝑣** and **𝑤**, is denoted as **𝑣 × 𝑤**. It is defined by the formula:

$$𝑣 × 𝑤 = ‖𝑣‖₂ ‖𝑤‖₂ \sin(𝜃) \, \mathbf{n}$$

where:
- **𝜃** is the angle between **𝑣** and **𝑤** (which can be computed using the dot product).
- **𝑛** is a vector perpendicular to both **𝑣** and **𝑤** with unit length (i.e., the length is one).

The geometric interpretation of the cross product is a vector that is perpendicular to both **𝑣** and **𝑤**, with a length equal to the area of the parallelogram formed by the two vectors.

### Linear Combinations

Assume that **𝑆** is a set where addition and scalar multiplication are defined. A **linear combination** of **𝑆** is defined as:

$$\sum \alpha_i s_i$$

where:
- **𝛼𝑖** is any real number, and
- **𝑠𝑖** is the 𝑖th object in **𝑆**.

The **𝛼𝑖** values are sometimes called the coefficients of **𝑠𝑖**. Linear combinations can describe various scenarios. For example, a grocery bill can be represented as **∑𝑐𝑖𝑛𝑖**, where **𝑐𝑖** is the cost of item **𝑖** and **𝑛𝑖** is the quantity of item **𝑖** purchased. Therefore, the total cost is a linear combination of the items purchased.

### Linear Independence

A set is called **linearly independent** if no object in the set can be written as a linear combination of the other objects in the set. For the purposes of this book, we will only consider the linear independence of a set of vectors. If a set of vectors is not linearly independent, it is considered **linearly dependent**.


In [40]:
# Compute the dot product between the vectors 𝑣 =[10,9,3] and transpose of 𝑤 =[2,5,12]
from numpy import  dot
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
w_transpose = w.T
dot_product = dot(v,w_transpose)
print(dot_product)

[[101]]


In [48]:
# Compute the angle between the vectors 𝑣 =[10,9,3] and 𝑤 =[2,5,12]
from numpy import arccos,   #arccos is the inverse of cos
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


In [71]:
# Given the vectors 𝑣=[0,2,0] and 𝑤=[3,0,0] use the Numpy function cross to compute the cross product of v and w.
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


### Matrices

An **𝑚 × 𝑛** matrix is a rectangular table of numbers consisting of **𝑚** rows and **𝑛** columns. The norm of a matrix can be considered as a particular kind of vector norm. If we treat the **𝑚 × 𝑛** elements of **𝑀** as the elements of an **𝑚𝑛** dimensional vector, then the **p-norm** of this vector can be written as:

$$‖𝑀‖𝑝 = \left(\sum_{𝑖=1}^{𝑚} \sum_{𝑗=1}^{𝑛} |𝑎𝑖𝑗|^𝑝 \right)^{\frac{1}{𝑝}}$$

You can calculate the matrix norm using the same `norm` function in NumPy as you would for a vector.

Matrix addition and scalar multiplication for matrices work the same way as they do for vectors. However, **matrix multiplication** between two matrices, **𝑃** and **𝑄**, is defined when **𝑃** is an **𝑚 × 𝑝** matrix and **𝑄** is a **𝑝 × 𝑛** matrix. The result of **𝑀 = 𝑃𝑄** is a matrix **𝑀** that is **𝑚 × 𝑛**. 

The dimension with size **𝑝** is called the **inner matrix dimension**, and the inner matrix dimensions must match (i.e., the number of columns in **𝑃** and the number of rows in **𝑄** must be the same) for matrix multiplication to be defined. The dimensions **𝑚** and **𝑛** are called the **outer matrix dimensions**. Formally, if **𝑃** is **𝑚 × 𝑝** and **𝑄** is **𝑝 × 𝑛**, then **𝑀 = 𝑃𝑄** is defined as:

$$𝑀𝑖𝑗 = \sum_{𝑘=1}^{𝑝} 𝑃𝑖𝑘 𝑄𝑘𝑗$$

In Python, the product of two matrices **𝑃** and **𝑄** is achieved by using the `dot` method in NumPy.

The **transpose** of a matrix is a reversal of its rows with its columns. The transpose is denoted by a superscript **𝑇**, such as **𝑀^𝑇** being the transpose of matrix **𝑀**. In Python, the `T` attribute for a NumPy array is used to get the transpose. For example, if **𝑀** is a matrix, then **𝑀.T** is its transpose.

### Square Matrices and Determinants

A **square matrix** is an **𝑛 × 𝑛** matrix, meaning it has the same number of rows as columns. The **determinant** is an important property of square matrices and is denoted by **det(𝑀)** in both mathematics and NumPy's `linalg` package. Sometimes, the determinant is also represented as **|𝑀|**.

#### Determinant of a 2×2 Matrix
For a 2×2 matrix, the determinant is calculated as:

$$|𝑀| = \begin{vmatrix} a & b \\ c & d \end{vmatrix} = ad - bc$$

#### Determinant of a 3×3 Matrix
For a 3×3 matrix, the determinant is calculated as:

$$|𝑀| = \begin{vmatrix} a & b & c \\ d & e & f \\ g & h & i \end{vmatrix} = a \begin{vmatrix} e & f \\ h & i \end{vmatrix} - b \begin{vmatrix} d & f \\ g & i \end{vmatrix} + c \begin{vmatrix} d & e \\ g & h \end{vmatrix}$$

Which simplifies to:

$$|𝑀| = a(ei - fh) - b(di - fg) + c(dh - eg)$$

The process can be extended to calculate the determinant for higher-dimensional matrices, but it's much easier to calculate using Python. We'll see an example of this later.

### Identity Matrix

The **identity matrix** is a square matrix with ones on the diagonal and zeros elsewhere. It is usually denoted by **𝐼** and is analogous to the real number identity, 1. Multiplying any matrix by **𝐼** (of compatible size) will produce the same matrix.

### Inverse of a Square Matrix

The **inverse** of a square matrix **𝑀** is a matrix of the same size, denoted as **𝑁**, such that **𝑀 ⋅ 𝑁 = 𝐼**, where **𝐼** is the identity matrix. The inverse of a matrix is analogous to the inverse of real numbers. For example, the inverse of 3 is **1/3** because **(3) × (1/3) = 1**.

A matrix is said to be **invertible** if it has an inverse. The inverse of a matrix is unique, meaning that for an invertible matrix, there is only one inverse. If **𝑀** is a square matrix, its inverse is denoted by **𝑀⁻¹** in mathematics and can be computed in Python using the `inv` function from NumPy's `linalg` package.

#### Inverse of a 2×2 Matrix
For a 2×2 matrix, the analytical solution of the matrix inverse is:

$$𝑀^{-1} = \begin{pmatrix} a & b \\ c & d \end{pmatrix}^{-1} = \frac{1}{|𝑀|} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$$

where **|𝑀|** is the determinant of the matrix **𝑀**.

As the matrix dimension increases, the calculation of the matrix inverse becomes more complex. Various methods can simplify this process, such as **Gaussian elimination**, **Newton's method**, **Eigendecomposition**, and others. We'll explore some of these methods after learning how to solve a system of linear equations, as the process is essentially the same.

### Singular and Nonsingular Matrices

Just as 0 has no inverse in the real-number system, some matrices do not have inverses. These matrices are called **singular**. Matrices that do have an inverse are called **nonsingular**.

One way to determine if a matrix is singular is by computing its determinant. If the determinant is 0, then the matrix is singular; otherwise, it is nonsingular.

### Ill-Conditioned Matrices

A matrix that is close to being **singular** (i.e., its determinant is close to 0) is called **ill-conditioned**. Although ill-conditioned matrices do have inverses, they pose numerical challenges. This is similar to dividing by a very small number, which can lead to overflow, underflow, or significant round-off errors. 

The **condition number** is a measure of how ill-conditioned a matrix is. You can compute it using NumPy's `cond` function from the `linalg` module. The higher the condition number, the closer the matrix is to being singular.

### Rank of a Matrix

The **rank** of an **𝑚 × 𝑛** matrix **𝐴** is the number of linearly independent columns or rows of **𝐴**, denoted as **rank(𝐴)**. It can be shown that the number of linearly independent rows is always equal to the number of linearly independent columns for any matrix.

A matrix is called **full rank** if **rank(𝐴) = min(𝑚, 𝑛)**. This means that all of its columns are linearly independent. 

An **augmented matrix** is a matrix **𝐴** concatenated with a vector **𝑦**, written as **[𝐴, 𝑦]**. This is commonly read as "𝐴 augmented with 𝑦." You can use `np.concatenate` in NumPy to concatenate them.

If **rank([𝐴, 𝑦]) = rank(𝐴) + 1**, then the vector **𝑦** represents "new" information. In other words, it cannot be expressed as a linear combination of the columns in **𝐴**. The rank of a matrix is crucial in understanding the solutions to linear equations, which will be discussed in the final section of this chapter.


In [ ]:
#Compute the matrix product of 𝑃 and 𝑄 
# 𝑃 =[[1,7],[2,3],[5,0]] and 𝑄=[[2,6,3,1],[1,2,3,4]]
# Show that the product of 𝑄 and 𝑃  will produce an error.
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))
np.dot(Q, P)

In [78]:
from numpy.linalg import det

M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [80]:
from numpy.linalg import inv

print('Inv M:\n', inv(M))
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(p):\n', det(P))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det(p):
 0.0


In [82]:
from numpy.linalg import  cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


### Solutions to Systems of Linear Equations

Consider a system of linear equations in matrix form, **𝐴𝑥 = 𝑦**, where **𝐴** is an **𝑚 × 𝑛** matrix. This system consists of **𝑚** equations and **𝑛** unknowns. A solution to the system is a vector **𝑥** in **ℝⁿ** that satisfies the equation. Depending on the values of **𝐴** and **𝑦**, there are three possible outcomes for **𝑥**: 
1. No solution,
2. One unique solution,
3. An infinite number of solutions.

#### 1. Gauss Elimination Method
The Gauss Elimination method is used to transform matrix **𝐴** into an upper triangular form to solve the system of equations. This form allows for easier computation of the variables using back-substitution.

#### 2. Gauss-Jordan Elimination Method
Gauss-Jordan Elimination is a method that transforms **𝐴** into a diagonal form, making it simpler to solve for the unknowns. The resulting matrix form is a simple form, where each equation directly gives the value of one unknown.

#### 3. LU Decomposition Method
The Gauss and Gauss-Jordan methods involve modifying both **𝐴** and **𝑦** simultaneously, which can be inefficient when solving multiple systems with different **𝑦** values but the same **𝐴** matrix. The LU decomposition method addresses this by decomposing **𝐴** into two matrices: **𝐿** (lower triangular) and **𝑈** (upper triangular). This approach allows for solving the system more efficiently.
This allows for solving the system in two steps: first by forward substitution to solve **𝐿𝑀 = 𝑦**, and then by backward substitution to solve **𝑈𝑥 = 𝑀**.

#### 4. Gauss-Seidel Method

The Gauss-Seidel Method is an iterative approach to solving systems of linear equations. This method updates each element in the solution vector **𝑥** using the most recent estimates.<br>
**Initial Guess:** Start by assuming initial values for **𝑥₂, 𝑥₃, …, 𝑥ₙ** (except **𝑥₁**).<br>
**Update:** Calculate **𝑥₁** using the current values of the other elements.<br>
**Iterate:** Using the newly calculated **𝑥₁** and the remaining elements of **𝑥** (except **𝑥₂**), update **𝑥₂**.<br>
**Repeat:** Continue this process for all elements in **𝑥** until you complete the first iteration.<br>
**Convergence:** Continue iterating until the values of **𝑥** converge to a stable solution.<br>

The key feature of the Gauss-Seidel method is that it always uses the most up-to-date value of each variable to compute the next one. This approach can lead to faster convergence compared to methods that use older values.


### Solve Systems of Linear Equations in Python

While we've explored various methods to solve systems of linear equations, Python offers a much simpler approach. In this section, we'll use Python to solve such systems with minimal effort.

The easiest way to solve a system of linear equations in Python is by using the `solve` function from the Numpy library.

#### Example:
Let's use `numpy.linalg.solve` to solve the following system of equations:
\
\begin{align*}
4x_1 + 3x_2 - 5x_3 &= 25 \\
-2x_1 - 4x_2 + 5x_3 &= -3 \\
8x_1 + 8x_2 &= 3
\end{align*}


In [176]:
#Use numpy.linalg.solve to solve the following equations.
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [101]:
# Solve the above equations using the matrix inversion approach.
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [103]:
# Verify the above 𝐿 and 𝑈  matrices are the LU decomposition of matrix 𝐴. We should see that 𝐴=𝐿𝑈
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


### Exercise 11.0  (80 marks)
1. Given the vector [[1, -5, 3, 2, 4]], calculates the Manhattan Distance, Euclidean_Distance and 𝐿∞ norm of a vector

2. Compute the dot and angle product between the vectors x =[7,8,9] and transpose of y =[1,2,4]

3. Given the vectors 𝑣=[1,2,4] and 𝑤=[3,6,9] use the Numpy function cross to compute the cross product of v and w.

#### For 
```plaintext
          ⎡ 0  7  1  3 ⎤
x =       ⎢ 3  7  8  1 ⎥
          ⎢ 1  0  0  3 ⎥
          ⎣ 0  3  7  1 ⎦

          
4. Find the Determinant of x

5. What is the identity Matrix of x

6. What is the inverse of x

7. What is the condition number and rank of x

8. Find the values for x1,x2,x3 in these equations:
\
\begin{align*}
6x_1 + 3x_2 - 7x_3 &= 25 \\
-2x_1 - 6x_2 + 5x_3 &= -3 \\
8x_1 + 4x_2 &= 3
\end{align*}

In [187]:
#Use numpy.linalg.solve to solve the following equations.
import numpy as np

x = np.array([[6, 3, -7], 
              [-2, -6, 5], 
              [8, 4, 0]])
y = np.array([25, -3, 3])

x1,x2,x3 = np.linalg.solve(x, y)
print('X1 = ',x1,'\t X2 = ',x2,'\t X3 = ',x3)

X1 =  1.775 	 X2 =  -2.8 	 X3 =  -3.25


## Lab Exercise 11.2 (20 marks)
Ensure you entered your full name and R Number in the top cell<br>
Convert to PDF and submit both PDF and IPYNB

___
## <font color=orange>This is a Numpy Cheat Sheet!</font>

![](https://blog.finxter.com/wp-content/uploads/2019/10/grafik-1-1024x725.png)

### Check out this link for more: <br>
https://blog.finxter.com/collection-10-best-numpy-cheat-sheets-every-python-coder-must-own/

___
![](https://media2.giphy.com/media/5nj4ZZWl6QwneEaBX4/source.gif) <br>

*Here are some of the resources used for creating this notebook:* 
- Johnson, J. (2020). Python Numpy Tutorial (with Jupyter and Colab). Retrieved September 15, 2020, from https://cs231n.github.io/python-numpy-tutorial/ <br>
- Willems, K. (2019). (Tutorial) Python NUMPY Array TUTORIAL. Retrieved September 15, 2020, from https://www.datacamp.com/community/tutorials/python-numpy-tutorial?utm_source=adwords_ppc <br>
- Willems, K. (2017). NumPy Cheat Sheet: Data Analysis in Python. Retrieved September 15, 2020, from https://www.datacamp.com/community/blog/python-numpy-cheat-sheet <br>
- W3resource. (2020). NumPy: Compare two given arrays. Retrieved September 15, 2020, from https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-28.php <br>



*Here are some great reads on this topic:* 
- __"Python NumPy Tutorial"__ available at *https://www.geeksforgeeks.org/python-numpy-tutorial/<br>
- __"What Is NumPy?"__ a collection of blogs, available at *https://realpython.com/tutorials/numpy/ <br>
- __"Look Ma, No For-Loops: Array Programming With NumPy"__ by __Brad Solomon__ available at *https://realpython.com/numpy-array-programming/ <br>
- __"The Ultimate Beginner’s Guide to NumPy"__ by __Anne Bonner__ available at *https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54 <br>


*Here are some great videos on these topics:* 
- __"Learn NUMPY in 5 minutes - BEST Python Library!"__ by __Python Programmer__ available at *https://www.youtube.com/watch?v=xECXZ3tyONo <br>
- __"Python NumPy Tutorial for Beginners"__ by __freeCodeCamp.org__ available at *https://www.youtube.com/watch?v=QUT1VHiLmmI <br>
- __"Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)"__ by __Keith Galli__ available at *https://www.youtube.com/watch?v=GB9ByFAIAH4 <br>
- __"Python NumPy Tutorial | NumPy Array | Python Tutorial For Beginners | Python Training | Edureka"__ by __edureka!__ available at *https://www.youtube.com/watch?v=8JfDAm9y_7s <br>

![](https://quotefancy.com/media/wallpaper/3840x2160/722175-Pythagoras-Quote-Number-rules-the-universe.jpg)