# <font color=darkred>Laboratory 10: Numpy 
</font>

In [ ]:
# Preamble script block to identify host, user, and kernel
import sys
! hostname
! whoami
print(sys.executable)
print(sys.version)
print(sys.version_info)

## Full name: 
## R#: 
## Title of the notebook:
## Date:
___

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/1280px-NumPy_logo_2020.svg.png) <br>

## <font color=purple>Numpy</font>
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. The library’s name is short for “Numeric Python” or “Numerical Python”. If you are curious about NumPy, this cheat sheet is recommended:
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

### <font color=purple>Arrays</font>

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension. In other words, an array contains information about the raw data, how to locate an element and how to interpret an element.To make a numpy array, you can just use the np.array() function. All you need to do is pass a list to it. Don’t forget that, in order to work with the np.array() function, you need to make sure that the numpy library is present in your environment.
If you want to read more about the differences between a Python list and NumPy array, this link is recommended:
https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference



___
### Example- 1D Arrays
__Let's create a 1D array from the 2000s (2000-2009):__ 

In [5]:
import numpy as np             #First, we need to import "numpy"
mylist = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009]         #Create a list of the years
print(mylist)                 #Check how it looks
np.array(mylist)              #Define it as a numpy array


[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]


array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009])

___
### Example- n-Dimensional Arrays
__Let's create a 5x2 array from the 2000s (2000-2009):__ 

In [ ]:
myotherlist = [[2000,2001],[2002,2003],[2004,2005],[2006,2007],[2008,2009]]     #Since I want a 5x2 array, I should group the years two by two
print(myotherlist)             #See how it looks as a list
np.array(myotherlist)          #See how it looks as a numpy array

### <font color=purple>Arrays Arithmetic</font>

Once you have created the arrays, you can do basic Numpy operations. Numpy offers a variety of operations applicable on arrays. From basic operations such as summation, subtraction, multiplication and division to more advanced and essential operations such as matrix multiplication and other elementwise operations. In the examples below, we will go over some of these:


___
### Example- 1D Array Arithmetic
- Define a 1D array with [0,12,24,36,48,60,72,84,96]
- Multiple all elements by 2
- Take all elements to the power of 2
- Find the maximum value of the array and its position
- Find the minimum value of the array and its position
- Define another 1D array with [-12,0,12,24,36,48,60,72,84]
- Find the summation and subtraction of these two arrays
- Find the multiplication of these two arrays

In [ ]:
import numpy as np         #import numpy
Array1 = np.array([0,12,24,36,48,60,72,84,96])     #Step1: Define Array1
print(Array1)
print(Array1*2)     #Step2: Multiple all elements by 2
print(Array1**2)     #Step3: Take all elements to the power of 2

print(np.power(Array1,2)) #Another way to do the same thing, by using a function in numpy
print(np.max(Array1))     #Step4: Find the maximum value of the array
print(np.argmax(Array1))     ##Step4: Find the postition of the maximum value 
print(np.min(Array1))     #Step5: Find the minimum value of the array
print(np.argmin(Array1))     ##Step5: Find the postition of the minimum value 

Array2 = np.array([-12,0,12,24,36,48,60,72,84])     #Step6: Define Array2
print(Array2)
print(Array1+Array2)         #Step7: Find the summation of these two arrays


___
### Example- n-Dimensional Array Arithmetic
- Define a 2x2 array with [5,10,15,20]
- Define another 2x2 array with [3,6,9,12]
- Find the summation and subtraction of these two arrays
- Find the minimum number in the multiplication of these two arrays
- Find the position of the maximum in the multiplication of these two arrays
- Find the mean of the multiplication of these two arrays
- Find the mean of the first row of the multiplication of these two arrays


In [ ]:
import numpy as np         #import numpy
Array1 = np.array([[5,10],[15,20]])     #Step1: Define Array1
print(Array1)
Array2 = np.array([[3,6],[9,12]])     #Step2: Define Array2
print(Array2)

print(Array1+Array2)     #Step3: Find the summation

MultArray = Array1@Array2         #Step4: To perform a typical matrix multiplication (or matrix product)
MultArray1 = Array1.dot(Array2)         #Step4: Another way To perform a  matrix multiplication

print(MultArray)
print(MultArray1)

print(np.mean(MultArray))     ##Step6: Find the mean of the multiplication of these two arrays 
print(np.mean(MultArray[0,:]))     ##Step7: Find the mean of the first row of the multiplication of these two arrays 


___
### <font color=purple>Arrays Comparison</font>


Comparing two NumPy arrays determines whether they are equivalent by checking if every element at each corresponding index are the same.

![](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-28.png)

___
### Example- 1D Array Comparison
- Define a 1D array with [1.0,2.5,3.4,7,7]
- Define another 1D array with [5.0/5.0,5.0/2,6.8/2,21/3,14/2]
- Compare and see if the two arrays are equal
- Define another 1D array with [6,1.4,2.2,7.5,7]
- Compare and see if the first array is greater than or equal to the third array

In [ ]:
import numpy as np         #import numpy
Array1 = np.array([1.0,2.5,3.4,7,7])     #Step1: Define Array1
print(Array1)
Array2 = np.array([5.0/5.0,5.0/2,6.8/2,21/3,14/2])     #Step2: Define Array1
print(Array2)
print(np.equal(Array1, Array2))             #Step3: Compare and see if the two arrays are equal
Array3 = np.array([6,1.4,2.2,7.5,7])     #Step4: Define Array3
print(Array3)
print(np.greater_equal(Array1, Array3))             #Step3: Compare and see if the two arrays are equal


___
### <font color=purple>Arrays Manipulation</font>

numpy.copy() allows us to create a copy of an array. This is particularly useful when we need to manipulate an array while keeping an original copy in memory.
The numpy.delete() function returns a new array with sub-arrays along an axis deleted. Let's have a look at the examples.


![](https://codetorial.net/numpy/_images/numpy_delete_01.png)
![](https://www.w3resource.com/w3r_images/numpy-manipulation-delete-function-image-1.png)

___
### Example- Copying and Deleting Arrays and Elements
- Define a 1D array, named "x" with [1,2,3]
- Define "y" so that "y=x"
- Define "z" as a copy of "x"
- Discuss the difference between y and z
- Delete the second element of x

In [ ]:
import numpy as np         #import numpy
x = np.array([1,2,3])     #Step1: Define x
print(x)
y = x                     #Step2: Define y as y=x
print(y)
z = np.copy(x)            #Step3: Define z as a copy of x
print(z)
# For Step4: They look similar but check this out:
x[1] = 8                  # If we change x ...
print(x)
print(y)
print(z)
# By modifying x, y changes but z remains as a copy of the initial version of x.
x = np.delete(x, 1)      #Step5: Delete the second element of x
print(x)

___
### <font color=purple>Sorting Arrays</font>

Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending. If you use the sort() method on a 2-D array, both arrays will be sorted.

![](https://www.w3resource.com/w3r_images/numpy-sorting-and-searching-image-exercise-1.svg)

___
### Example- Sorting 1D Arrays
__Define a 1D array as ['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'] and print it out. Then, sort the array alphabetically.__


In [ ]:
import numpy as np         #import numpy
games = np.array(['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'])
print(games)
print(np.sort(games))

___
### Example- Sorting n-Dimensional Arrays
__Define a 3x3 array with 17,-6,2,86,-12,0,0,23,12 and print it out. Then, sort the array.__

In [ ]:
import numpy as np         #import numpy
a = np.array([[17,-6,2],[86,-12,0],[0,23,12]])
print(a)
print ("Along columns : \n", np.sort(a,axis = 0) ) #This will be sorting in each column
print ("Along rows : \n", np.sort(a,axis = 1) ) #This will be sorting in each row
print ("Sorting by default : \n", np.sort(a) )          #Same as above
print ("Along None Axis : \n", np.sort(a,axis = None) ) #This will be sorted like a 1D array


___
### <font color=purple>Partitioning (Slice) Arrays</font>


Slicing in python means taking elements from one given index to another given index.

We can do slicing like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

![](https://media.geeksforgeeks.org/wp-content/uploads/Numpy1.jpg)

___
### Example- Slicing 1D Arrays
__Define a 1D array as [1,3,5,7,9], slice out the [3,5,7] and print it out.__

In [ ]:
import numpy as np         #import numpy
a = np.array([1,3,5,7,9])     #Define the array
print(a)
aslice = a[1:4]             #slice the [3,5,7]
print(aslice)               #print it out


___
### Example- Slicing n-Dimensional Arrays
__Define a 5x5 array with "Superman, Batman, Jim Hammond, Captain America, Green Arrow, Aquaman, Wonder Woman, Martian Manhunter, Barry Allen, Hal Jordan, Hawkman, Ray Palmer, Spider Man, Thor, Hank Pym, Solar, Iron Man, Dr. Strange, Daredevil, Ted Kord, Captian Marvel, Black Panther, Wolverine, Booster Gold, Spawn " and print it out. Then:__
- Slice the first column and print it out
- Slice the third row and print it out
- Slice 'Wolverine' and print it out
- Slice a 3x3 array with 'Wonder Woman, Ray Palmer, Iron Man, Martian Manhunter, Spider Man, Dr. Strange, Barry Allen, Thor, Daredevil'

In [ ]:
import numpy as np         #import numpy
Superheroes = np.array([['Superman', 'Batman', 'Jim Hammond', 'Captain America', 'Green Arrow'],
               ['Aquaman', 'Wonder Woman', 'Martian Manhunter', 'Barry Allen', 'Hal Jordan'],
               ['Hawkman', 'Ray Palmer', 'Spider Man', 'Thor', 'Hank Pym'],
               ['Solar', 'Iron Man', 'Dr. Strange', 'Daredevil', 'Ted Kord'],
               ['Captian Marvel', 'Black Panther', 'Wolverine', 'Booster Gold', 'Spawn']])
print(Superheroes) #Step1
print(Superheroes[:,0])
print(Superheroes[2,:])
print(Superheroes[4,2])
print(Superheroes[1:4,1:4])

### Trigonometric Functions

NumPy provides several universal functions (ufuncs) for trigonometric operations:

- `sin()`
- `cos()`
- `tan()`

These functions take values in radians and return the corresponding sine, cosine, and tangent values.

#### Finding Angles

To find angles from sine, cosine, or tangent values, you can use the following inverse functions:

- `arcsin()` for the inverse sine
- `arccos()` for the inverse cosine
- `arctan()` for the inverse tangent


#### Convert Degrees to Radians

By default, all trigonometric functions in NumPy use radians. To convert degrees to radians and vice versa, you can use NumPy functions:

1. To convert degrees to radians, you use the following formula:
\begin{align*}
\text{radians} = \text{degrees} \times \left(\frac{\pi}{180}\right)
\end{align*}
- Using numpy use **`np.deg2rad(degrees)`** to convert degrees to radians
2. To convert radians to degrees, you use the following formula:
\begin{align*}
\text{degrees} = \text{radians} \times \left(\frac{180}{\pi}\right)
\end{align*}
- Using numpy use **`np.rad2deg(radians)`** to convert radians to degrees


#### Hypotenuse

To find the hypotenuse of a right triangle using the Pythagorean theorem, you can use the `hypot()` function:

- `np.hypot(base, perpendicular)`

This function takes the base and perpendicular values and returns the hypotenuse based on the Pythagorean theorem.


In [113]:
# Find sine values for all of the values in arr:
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [119]:
#Convert all of the values in following array arr to radians:
import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [117]:
#Find the angle for all of the sine values in the array
import numpy as np
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


### Exercise 10.1  (40 marks)
1. List 5 ways we can differenciates between Python lists and Numpy arrays?


2. Modify the given Array by slicing 

>                    [[1,   2,  3,  4,  5],
>                     [6,   7,  8,  9, 10],
>                     [11, 12, 13, 14, 15],
>                     [16, 17, 18, 19, 20]] 
  
  
 to make it look like
>                         [[ 7  8  9] 
>                          [12 13 14]]



3. In NumPy, what does the SHAPE of an array mean and how do we check the shape of this array. <br>
```plaintext
          ⎡ 0  7  1  3 ⎤
x =       ⎢ 3  7  8  1 ⎥
          ⎢ 1  0  0  3 ⎥
          ⎣ 0  3  7  1 ⎦


4. What is a correct syntax to print the number 8 from the array below:<br>
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

5. What is the correct formula to convert 50 degrees into radians and write the numpy code?
    1. `np.pi / 180 * 50`
    2. `np.pi / 50 / 180`
    3. `180 * np.pi / 50`


6. Create two numpy 2d arrays. The first 2d array should have the size 3by4 and second should have the size 4by5.
Use random library to generate the numbers (it should be an integer 2d array where the range for the integers is [1,10])

7. You are working on an engineering project where you need to analyze a set of sensor data in real-time. The sensor data is provided as a NumPy array sensor_data of shape (m,n), where m is the number of sensors and n is the number of readings.

    You need to perform the following tasks on the sensor data using NumPy:
    
    Normalize the data to have zero mean and unit variance across all sensors.
    Remove any outliers in the data using the interquartile range (IQR) method.
    Compute the correlation matrix of the normalized and cleaned data.
    Write a NumPy code snippet to perform the above tasks on the sensor_data array. Your code should return the correlation matrix as a NumPy array of shape (m,m). You can assume that the input sensor_data array contains only numerical data.<br>
    - Use sensor_data = np.random.randint(X,Y,(4,100)).
    - X is the first two letters of your Rnumber.
    - Y is the last four letters of your Rnumber.<br>
    Can't start with zero, if zero replace with 1

In [28]:
import numpy as np
sensor_data = np.random.randint(11,125,(4,100))
# Step 1: Normalize the data
mean = np.mean(sensor_data, axis=1)
std = np.std(sensor_data, axis=1)
sensor_data_norm = (sensor_data - mean.reshape(-1, 1)) / std.reshape(-1, 1)

# Step 2: Remove outliers
q1 = np.percentile(sensor_data_norm, 25, axis=1)
q3 = np.percentile(sensor_data_norm, 75, axis=1)
iqr = q3 - q1
lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
mask = np.logical_and(sensor_data_norm > lower.reshape(-1, 1), sensor_data_norm < upper.reshape(-1, 1))
sensor_data_clean = np.where(mask, sensor_data_norm, np.nan)

# Step 3: Compute the correlation matrix
correlation_matrix = np.corrcoef(sensor_data_clean, rowvar=False)

8. You are working on an engineering project where you need to analyze a set of temperature readings in real-time. The temperature readings are provided as a NumPy array temp_data of shape (m,n), where m is the number of sensors and n is the number of readings.

    You need to perform the following tasks on the temperature data using NumPy:
    
    Convert the temperature data from Celsius to Fahrenheit.
    Identify the sensor that has the highest average temperature across all readings.
    Compute the moving average of the temperature readings for each sensor using a window of size k, where k is an odd integer.
    Write a NumPy code snippet to perform the above tasks on the temp_data array. Your code should return the moving average temperature data as a NumPy array of the same shape as the input array. You can assume that the input temp_data array contains only numerical data.


In [9]:
import numpy as np
temp_data = np.random.normal(2,10,(2,10))
# Step 1: Convert the temperature data from Celsius to Fahrenheit
temp_data_F = temp_data * 1.8 + 32

# Step 2: Identify the sensor that has the highest average temperature
avg_temp = np.mean(temp_data_F, axis=1)
sensor_idx = np.argmax(avg_temp)

# Step 3: Compute the moving average of the temperature readings for each sensor
k = 3  # window size
pad_width = (k // 2, k // 2)
temp_data_F_padded = np.pad(temp_data_F, [(0,0), pad_width], mode='edge')
kernel = np.ones(k) / k
temp_data_F_moving_avg = np.apply_along_axis(lambda x: np.convolve(x, kernel, mode='valid'), axis=1, arr=temp_data_F_padded)
print(temp_data_F_moving_avg)

[[50.71697878 42.80651693 25.7971477  15.88280172  9.12663164 26.09920621
  29.21383449 35.33479075 36.34459503 49.04578765]
 [45.73364542 53.27817115 43.03546702 43.24799944 39.64937609 46.20159072
  35.70115773 35.36252355 41.10384421 55.6826321 ]]


In [7]:
temp_data_F_moving_avg

array([[25.68360657, 27.01696587, 35.2319139 , 31.59171132, 37.41951439,
        12.4909819 , 20.35002944, 17.39766958, 46.50460098, 51.76228154],
       [18.87224595, 28.1437438 , 37.53401956, 39.40835065, 46.60075082,
        47.6093854 , 41.40547601, 29.69351238, 23.61639808, 24.87415727]])

## Lab Exercise 10.2 (20 marks)
Ensure you entered your full name and R Number in the top cell<br>
Convert to PDF and submit both PDF and IPYNB

___
## <font color=orange>This is a Numpy Cheat Sheet!</font>

![](https://blog.finxter.com/wp-content/uploads/2019/10/grafik-1-1024x725.png)

### Check out this link for more: <br>
https://blog.finxter.com/collection-10-best-numpy-cheat-sheets-every-python-coder-must-own/

___
![](https://media2.giphy.com/media/5nj4ZZWl6QwneEaBX4/source.gif) <br>

*Here are some of the resources used for creating this notebook:* 
- Johnson, J. (2020). Python Numpy Tutorial (with Jupyter and Colab). Retrieved September 15, 2020, from https://cs231n.github.io/python-numpy-tutorial/ <br>
- Willems, K. (2019). (Tutorial) Python NUMPY Array TUTORIAL. Retrieved September 15, 2020, from https://www.datacamp.com/community/tutorials/python-numpy-tutorial?utm_source=adwords_ppc <br>
- Willems, K. (2017). NumPy Cheat Sheet: Data Analysis in Python. Retrieved September 15, 2020, from https://www.datacamp.com/community/blog/python-numpy-cheat-sheet <br>
- W3resource. (2020). NumPy: Compare two given arrays. Retrieved September 15, 2020, from https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-28.php <br>



*Here are some great reads on this topic:* 
- __"Python NumPy Tutorial"__ available at *https://www.geeksforgeeks.org/python-numpy-tutorial/<br>
- __"What Is NumPy?"__ a collection of blogs, available at *https://realpython.com/tutorials/numpy/ <br>
- __"Look Ma, No For-Loops: Array Programming With NumPy"__ by __Brad Solomon__ available at *https://realpython.com/numpy-array-programming/ <br>
- __"The Ultimate Beginner’s Guide to NumPy"__ by __Anne Bonner__ available at *https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54 <br>


*Here are some great videos on these topics:* 
- __"Learn NUMPY in 5 minutes - BEST Python Library!"__ by __Python Programmer__ available at *https://www.youtube.com/watch?v=xECXZ3tyONo <br>
- __"Python NumPy Tutorial for Beginners"__ by __freeCodeCamp.org__ available at *https://www.youtube.com/watch?v=QUT1VHiLmmI <br>
- __"Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)"__ by __Keith Galli__ available at *https://www.youtube.com/watch?v=GB9ByFAIAH4 <br>
- __"Python NumPy Tutorial | NumPy Array | Python Tutorial For Beginners | Python Training | Edureka"__ by __edureka!__ available at *https://www.youtube.com/watch?v=8JfDAm9y_7s <br>

![](https://quotefancy.com/media/wallpaper/3840x2160/722175-Pythagoras-Quote-Number-rules-the-universe.jpg)